import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  communitySidebar: [
    {
      "type": "category",
      "label": "Introduction",
      "items": [
        "intro/product_intro",
        "intro/product_scenarios",
        "intro/product_advantage",
        "intro/product_arch",
        "intro/product_nouns"
      ]
    },
    {
      "type": "doc",
      "id": "price/product_price",
    },
    {
      "type": "doc",
      "id": "price/plans_diff",
    },
    {
      "type": "doc",
      "id": "license/license_use"
    },
    {
      "type": "category",
      "label": "Quickstart",
      "items": [
        "quick/quick_start_mgr",
        "quick/quick_start_byoc",
        "quick/quick_start"
      ]
    },
    {
      "type": "category",
      "label": "Guides",
      "items": [
        {
          "type": "category",
          "label": "DataJob",
          "items": [
            {
              "type": "category",
              "label": "Creation",
              "items": [
                "operation/job_manage/create_job/create_full_incre_task",
                "operation/job_manage/create_job/create_process_job",
                "operation/job_manage/create_job/create_data_filter_job",
                "operation/job_manage/create_job/create_period_full_job",
                "operation/job_manage/create_job/create_regex_table_job",
                "operation/job_manage/create_job/create_period_verification_correction_job"
              ]
            },
            {
              "type": "category",
              "label": "Management",
              "items": [
                "operation/job_manage/job_op/job_life_cycle_manage",
                "operation/job_manage/job_op/job_detail",
                "operation/job_manage/job_op/job_log",
                "operation/job_manage/job_op/job_monitor",
                "operation/job_manage/job_op/job_params",
                "operation/job_manage/job_op/edit_job",
                "operation/job_manage/job_op/job_position",
                "operation/job_manage/job_op/job_schedule",
                "operation/job_manage/job_op/job_replay",
                "operation/job_manage/job_op/job_alarm",
                "operation/job_manage/job_op/create_similar_job",
                "operation/job_manage/job_op/debug_customer_code",
                "operation/job_manage/job_op/log_in_customer_code",
                "operation/job_manage/job_op/job_restart_record",
                "operation/job_manage/job_op/job_transfer",
                "operation/job_manage/job_op/job_group",
                "operation/job_manage/job_op/change_job_setting",
                "operation/job_manage/job_op/data_transform",
                "operation/job_manage/job_op/visual_widetable_create"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "Sync Settings",
          "items": [
            {
              "type": "category",
              "label": "Worker",
              "items": [
                "operation/job_setting/worker/cluster_manage",
                "operation/job_setting/worker/worker_manage",
                "operation/job_setting/worker/worker_monitor_alarm",
                "operation/job_setting/worker/worker_log",
                "operation/job_setting/worker/oversell_mac_memory",
              ]
            },
            "operation/job_setting/exception_manage",
            "operation/job_setting/console_job_manage",
            "operation/job_setting/check_alarm_log",
            "operation/job_setting/fsm_manage",
            "operation/job_setting/operate_audit"
          ]
        },
        {
          "type": "category",
          "label": "DataSource",
          "items": [
            "operation/datasource_manage/add_self_maintain_ds",
            "operation/datasource_manage/add_aws_ds",
            "operation/datasource_manage/add_azure_ds",
            "operation/datasource_manage/add_aliyun_ds",
            "operation/datasource_manage/ds_manage",
            "operation/datasource_manage/set_ssh_tunnel"
          ]
        },
        {
          "type": "category",
          "label": "Settings",
          "items": [
            "operation/system_manage/mfa_usage",
            "operation/system_manage/env_manage",
            "operation/system_manage/operate_audit",
            "operation/system_manage/preference",
            "operation/system_manage/third_party_setting"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Connection",
      "items": [
        "dataMigrationAndSync/datasource_version",
        {
          "type": "category",
          "label": "General Parameters",
          "items": [
            "dataMigrationAndSync/param_and_func/param_guide",
            "dataMigrationAndSync/param_and_func/print_message_detail",
            "dataMigrationAndSync/param_and_func/zero",
            "dataMigrationAndSync/param_and_func/write_time_limit",
            "dataMigrationAndSync/param_and_func/perf_param",
            "dataMigrationAndSync/param_and_func/skip_write_error",
            "dataMigrationAndSync/param_and_func/adjust_task_spec"
          ]
        },
        "dataMigrationAndSync/monitor",
        {
          "type": "category",
          "label": "Source",
          "items": [
            "dataMigrationAndSync/connection/mysql2",
            "dataMigrationAndSync/connection/mariadb2",
            "dataMigrationAndSync/connection/auroraformysql2",
            "dataMigrationAndSync/connection/polardbmysql2",
            "dataMigrationAndSync/connection/oracle2",
            "dataMigrationAndSync/connection/hana2",
            "dataMigrationAndSync/connection/redis2",
            "dataMigrationAndSync/connection/postgresql2",
            "dataMigrationAndSync/connection/auroraforpg",
            "dataMigrationAndSync/connection/opengauss2",
            "dataMigrationAndSync/connection/sqlserver2",
            "dataMigrationAndSync/connection/oceanbase2",
            "dataMigrationAndSync/connection/tidb2",
            "dataMigrationAndSync/connection/polardbx2",
            "dataMigrationAndSync/connection/db22",
            "dataMigrationAndSync/connection/starrocks2",
            "dataMigrationAndSync/connection/mongodb2",
            "dataMigrationAndSync/connection/kafka2",
            "dataMigrationAndSync/connection/automq2",
            "dataMigrationAndSync/connection/rocketmq2",
            "dataMigrationAndSync/connection/rabbitmq2",
            "dataMigrationAndSync/connection/tunnel2",
            "dataMigrationAndSync/connection/obfororacle2",
            "dataMigrationAndSync/connection/pulsar2",
            "dataMigrationAndSync/connection/tdengine2",
            "dataMigrationAndSync/connection/spanner2",
          ]
        },
        // {
        //   "type": "category",
        //   "label": "Target",
        //   "items": [
        //     "dataMigrationAndSync/target/MySQL",
        //     "dataMigrationAndSync/target/MariaDB",
        //     "dataMigrationAndSync/target/TiDB",
        //     "dataMigrationAndSync/target/PostgreSQL",
        //     "dataMigrationAndSync/target/Greenplum",
        //     "dataMigrationAndSync/target/ElasticSearch",
        //     "dataMigrationAndSync/target/ClickHouse",
        //     "dataMigrationAndSync/target/Kafka",
        //     "dataMigrationAndSync/target/RocketMQ",
        //     "dataMigrationAndSync/target/RabbitMQ",
        //     "dataMigrationAndSync/target/Hive",
        //     "dataMigrationAndSync/target/Oracle",
        //     "dataMigrationAndSync/target/Kudu",
        //     "dataMigrationAndSync/target/MongoDB",
        //     "dataMigrationAndSync/target/SQLServer",
        //     "dataMigrationAndSync/target/Redis",
        //     "dataMigrationAndSync/target/StarRocks",
        //     "dataMigrationAndSync/target/Doris",
        //     "dataMigrationAndSync/target/OceanBase",
        //     "dataMigrationAndSync/target/PolarDB-X",
        //     "dataMigrationAndSync/target/Tunnel",
        //     "dataMigrationAndSync/target/ADB for MySQL",
        //     "dataMigrationAndSync/target/PolarDB for MySQL",
        //     "dataMigrationAndSync/target/GaussDB for OpenGauss",
        //     "dataMigrationAndSync/target/GaussDB for MySQL"
        //   ]
        // }
        {
          "type": "category",
          "label": "DataSource Configuration",
          "items": [
            {
              "type": "category",
              "label": "MySQL",
              "items": [
                "dataMigrationAndSync/datasource_func/MySQL/privs_for_mysql",
                "dataMigrationAndSync/datasource_func/MySQL/open_mysql_heartbeat"
              ]
            },
            {
              "type": "category",
              "label": "Oracle",
              "items": [
                "dataMigrationAndSync/datasource_func/Oracle/privs_for_oracle",
                "dataMigrationAndSync/datasource_func/Oracle/prepare_for_oracle_logminer",
                "dataMigrationAndSync/datasource_func/Oracle/prepare_for_oracle_olr"
              ]
            },
            {
              "type": "category",
              "label": "PostgreSQL",
              "items": [
                "dataMigrationAndSync/datasource_func/PostgreSQL/privs_for_pg",
                "dataMigrationAndSync/datasource_func/PostgreSQL/open_pg_heartbeat"
              ]
            },
            {
              "type": "category",
              "label": "SQL Server",
              "items": [
                "dataMigrationAndSync/datasource_func/SqlServer/enable_sql_server_heartbeat",
                "dataMigrationAndSync/datasource_func/SqlServer/privs_for_sqlserver",
                "dataMigrationAndSync/datasource_func/SqlServer/update_multi_pos"
              ]
            },
            {
              "type": "category",
              "label": "Kafka",
              "items": [
                "dataMigrationAndSync/datasource_func/Kafka/privs_for_kafka",
                "dataMigrationAndSync/datasource_func/Kafka/open_kafka_heartbeat",
                "dataMigrationAndSync/datasource_func/Kafka/kafka_iam_auth"
              ]
            },
            {
              "type": "category",
              "label": "TiDB",
              "items": [
                "dataMigrationAndSync/datasource_func/TiDB/privs_for_tidb"
              ]
            },
            {
              "type": "category",
              "label": "MongoDB",
              "items": [
                "dataMigrationAndSync/datasource_func/MongoDB/privs_for_mongo",
                "dataMigrationAndSync/datasource_func/MongoDB/open_mongodb_heartbeat"
              ]
            },
            {
              "type": "category",
              "label": "Elasticsearch",
              "items": [
                "dataMigrationAndSync/datasource_func/ElasticSearch/prepare_for_es_as_src"
              ]
            },
            {
              "type": "category",
              "label": "SAP HANA",
              "items": [
                "dataMigrationAndSync/datasource_func/Hana/privs_for_hana",
                "dataMigrationAndSync/datasource_func/Hana/sap_hana_ddl"
              ]
            },
            {
              "type": "category",
              "label": "TDengine",
              "items": [
                "dataMigrationAndSync/datasource_func/TDengine/privs_for_tdengine"
              ]
            },
            {
              "type": "category",
              "label": "Db2",
              "items": [
                "dataMigrationAndSync/datasource_func/Db2/prepare_for_db2"
              ]
            },
            {
              "type": "category",
              "label": "Iceberg",
              "items": [
                "dataMigrationAndSync/datasource_func/Iceberg/props_for_iceberg_ds"
              ]
            },
            {
              "type": "category",
              "label": "Paimon",
              "items": [
                "dataMigrationAndSync/datasource_func/Paimon/props_for_paimon_ds"
              ]
            },
            {
              "type": "category",
              "label": "DynamoDB",
              "items": [
                "dataMigrationAndSync/datasource_func/DynamoDB/privs_for_dynamodb"
              ]
            },
            {
              "type": "category",
              "label": "Dameng",
              "items": [
                "dataMigrationAndSync/datasource_func/Dameng/privs_for_dameng",
                "dataMigrationAndSync/datasource_func/Dameng/prepare_for_dameng_logminer"
              ]
            },
            {
              "type": "category",
              "label": "Spanner",
              "items": [
                "dataMigrationAndSync/datasource_func/Spanner/privs_for_spanner"
              ]
            },
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Deployment",
      "items": [
        {
          "type": "category",
          "label": "On-Premise",
          "items": [
            {
              "type": "category",
              "label": "Installation",
              "items": [
                "productOP/onPremise/installation/install_all_in_one_docker",
                "productOP/onPremise/installation/add_worker_docker",
                "productOP/onPremise/installation/upgrade_all_in_one_docker",
                "productOP/onPremise/installation/uninstall_all_in_one_docker",
                "productOP/onPremise/installation/install_all_in_one_k8s",
                "productOP/onPremise/installation/upgrade_all_in_one_k8s",
                "productOP/onPremise/installation/uninstall_all_in_one_k8s",
                "productOP/onPremise/installation/install_all_in_one_binary",
                "productOP/onPremise/installation/add_worker_binary",
                "productOP/onPremise/installation/upgrade_all_in_one_binary"
              ]
            },
            {
              "type": "category",
              "label": "Maintenance",
              "items": [
                "productOP/onPremise/maintenance/minimal_docker_for_centos",
                "productOP/onPremise/maintenance/minimal_k8s_for_centos",
                "productOP/onPremise/maintenance/change_verify_code_777777",
                "productOP/onPremise/maintenance/change_on_premise_password",
                "productOP/onPremise/maintenance/change_ak_sk",
                "productOP/onPremise/maintenance/change_console_config",
                "productOP/onPremise/maintenance/get_log",
                "productOP/onPremise/maintenance/alarm_conf",
                "productOP/onPremise/maintenance/create_slack_group",
                "productOP/onPremise/maintenance/create_discord_group",
                "productOP/onPremise/maintenance/create_custom_alarm",
                "productOP/onPremise/maintenance/clear_worker_log"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "BYOC",
          "items": [
            {
              "type": "category",
              "label": "Installation",
              "items": [
                "productOP/byoc/installation/install_worker_docker",
                "productOP/byoc/installation/upgrade_worker_docker",
                "productOP/byoc/installation/uninstall_worker_docker",
                "productOP/byoc/installation/install_worker_binary",
                "productOP/byoc/installation/upgrade_worker_binary",
                "productOP/byoc/installation/uninstall_worker_binary"
              ]
            },
            {
              "type": "category",
              "label": "Maintenance",
              "items": [
                "productOP/byoc/maintenance/worker_network",
                "productOP/byoc/maintenance/get_log",
                "productOP/byoc/maintenance/change_console_sidecar_mem",
                "productOP/byoc/maintenance/alarm_conf",
                "productOP/byoc/maintenance/create_slack_group",
                "productOP/byoc/maintenance/create_discord_group",
                "productOP/byoc/maintenance/create_custom_alarm",
                "productOP/byoc/maintenance/clear_worker_log"
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Best Practices",
      "items": [
        "bestPractice/file_to_aliyun_pg_vector",
        "bestPractice/pg_vector_to_rag_api",
        "bestPractice/mysql_loop_data_sync",
        "bestPractice/redis_loop_data_sync",
        "bestPractice/http_internet_data_sync",
        "bestPractice/encrypt_data_when_sync",
        "bestPractice/verification_and_correction",
        "bestPractice/data_gather_use_virtual_cols",
        "bestPractice/time_schedule_full"
      ]
    },
    {
      "type": "category",
      "label": "FAQ",
      "items": [
        "faq/bladepipe_faq_list",
        "faq/performance_optimization",
        "faq/solve_task_communicate_timeout",
        "faq/solve_task_can_not_delete",
        "faq/solve_db_connect_fail",
        "faq/solve_data_inconsistent",
        "faq/solve_incre_task_delay",
        "faq/solve_mysql_src_json_invalid",
        "faq/solve_schedule_task_fail",
        "faq/solve_hana_test_connection_fail",
        "faq/solve_mysql_src_could_not_find_binlog",
        "faq/solve_sqlserver_tls",
        "faq/solve_sr_dr_dst_writer_http_host",
        "faq/solve_structure_migration_error",
        "faq/solve_access_denied_schema"
      ]
    },
    {
      "type": "category",
      "label": "Open API",
      "items": [
        {
          "type": "doc",
          "id": "openCenter/openApi/apiUseReference/api_common_parameters"
        },
        {
          "type": "category",
          "label": "Constant",
          "items": [
            "openCenter/openApi/constApi/api_constant_cachevalueformats",
            "openCenter/openApi/constApi/api_constant_cktableengines",
            "openCenter/openApi/constApi/api_constant_dscharset",
            "openCenter/openApi/constApi/api_constant_dsdeploytypes",
            "openCenter/openApi/constApi/api_constant_dsmappingmeta",
            "openCenter/openApi/constApi/api_constant_dspostype",
            "openCenter/openApi/constApi/api_constant_dstdstype",
            "openCenter/openApi/constApi/api_constant_listdatajobtype",
            "openCenter/openApi/constApi/api_constant_listspecs",
            "openCenter/openApi/constApi/api_constant_listdatataskstatuses",
            "openCenter/openApi/constApi/api_constant_listdatataskstates",
            "openCenter/openApi/constApi/api_constant_mqvalueformats",
            "openCenter/openApi/constApi/api_constant_srcdstype",
            "openCenter/openApi/constApi/api_constant_transformjobtype",
            "openCenter/openApi/constApi/api_constant_valueformatstemplate"
          ]
        },
        {
          "type": "category",
          "label": "Worker",
          "items": [
            "openCenter/openApi/clusterApi/api_cluster_listclusters",
            "openCenter/openApi/clusterApi/api_cluster_listworkers",
            "openCenter/openApi/clusterApi/api_cluster_createandinstallworker",
            "openCenter/openApi/clusterApi/api_cluster_operateworkersclient"
          ]
        },
        {
          "type": "category",
          "label": "DataSource",
          "items": [
            "openCenter/openApi/dataSourceApi/api_datasource_addds",
            "openCenter/openApi/dataSourceApi/api_datasource_listds",
            "openCenter/openApi/dataSourceApi/api_datasource_deleteaccount",
            "openCenter/openApi/dataSourceApi/api_datasource_updateaccountandpassword",
            "openCenter/openApi/dataSourceApi/api_datasource_updatealiyunrdsaksk",
            "openCenter/openApi/dataSourceApi/api_datasource_updatedatasourcedesc",
            "openCenter/openApi/dataSourceApi/api_datasource_updateprivatehost",
            "openCenter/openApi/dataSourceApi/api_datasource_updatepublichost",
            "openCenter/openApi/dataSourceApi/api_datasource_queryds",
            "openCenter/openApi/dataSourceApi/api_datasource_connectds",
            "openCenter/openApi/dataSourceApi/api_datasource_listdbs",
            "openCenter/openApi/dataSourceApi/api_datasource_tablecount",
            "openCenter/openApi/dataSourceApi/api_datasource_listtables",
            "openCenter/openApi/dataSourceApi/api_datasource_listcols",
            "openCenter/openApi/dataSourceApi/api_datasource_listuniqs",
            "openCenter/openApi/dataSourceApi/api_datasource_listtypemapping",
            "openCenter/openApi/dataSourceApi/api_datasource_deleteds",
            "openCenter/openApi/dataSourceApi/api_datasource_querydsconfig",
            "openCenter/openApi/dataSourceApi/api_datasource_upsertdsconfig"
          ]
        },
        {
          "type": "category",
          "label": "DataJob",
          "items": [
            "openCenter/openApi/dataTaskApi/api_datajob_list",
            "openCenter/openApi/dataTaskApi/api_datajob_query",
            "openCenter/openApi/dataTaskApi/api_datajob_queryjobschema",
            "openCenter/openApi/dataTaskApi/api_datajob_start",
            "openCenter/openApi/dataTaskApi/api_datajob_stop",
            "openCenter/openApi/dataTaskApi/api_datajob_restart",
            "openCenter/openApi/dataTaskApi/api_datajob_replay",
            "openCenter/openApi/dataTaskApi/api_datajob_attachincretask",
            "openCenter/openApi/dataTaskApi/api_datajob_detachincretask",
            "openCenter/openApi/dataTaskApi/api_datajob_activefsm",
            "openCenter/openApi/dataTaskApi/api_datajob_precheckbasic",
            "openCenter/openApi/dataTaskApi/api_datajob_precheckdetail",
            "openCenter/openApi/dataTaskApi/api_datajob_create",
            "openCenter/openApi/dataTaskApi/api_datajob_updatedesc",
            "openCenter/openApi/dataTaskApi/api_datajob_updatelevel",
            "openCenter/openApi/dataTaskApi/api_datajob_updatetransferobjnew",
            "openCenter/openApi/dataTaskApi/api_datajob_updatetransferobjnewfull",
            "openCenter/openApi/dataTaskApi/api_datajob_delete",
            "openCenter/openApi/dataTaskApi/api_datajob_updateincrepos",
            "openCenter/openApi/dataTaskApi/api_datajob_schema",
            "openCenter/openApi/dataTaskApi/api_datajob_mapping",
            "openCenter/openApi/dataTaskApi/api_datajob_listkvconfigsbyjobid",
            "openCenter/openApi/dataTaskApi/api_datajob_upsertkvconfigs"
          ]
        },
        {
          "type": "category",
          "label": "MetaData",
          "items": [
            "openCenter/openApi/schemaApi/api_schema_querybytransferobjname"
          ]
        },
        {
          "type": "category",
          "label": "ConsoleJob",
          "items": [
            "openCenter/openApi/asyncTaskApi/api_consolejob_queryconsolejob",
            "openCenter/openApi/asyncTaskApi/api_consolejob_retrytask"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Release Note",
      "items": [
        "releaseNote/rn-bladepipe-1-4-0",
        "releaseNote/rn-bladepipe-1-3-0",
        "releaseNote/rn-bladepipe-1-2-0",
        "releaseNote/rn-bladepipe-1-1-0",
        "releaseNote/rn-bladepipe-1-0-0",
        "releaseNote/rn-bladepipe-0-9-0",
        "releaseNote/rn-bladepipe-0-8-0",
        "releaseNote/rn-bladepipe-0-7-0",
        "releaseNote/rn-bladepipe-0-6-0",
        "releaseNote/rn-bladepipe-0-5-0",
        "releaseNote/rn-bladepipe-0-4-0",
        "releaseNote/rn-bladepipe-0-3-0",
        "releaseNote/rn-bladepipe-0-2-0",
        "releaseNote/rn-bladepipe-0-1-0",
        "releaseNote/rn-bladepipe-0-0-1"
      ]
    },
    {
      "type": "category",
      "label": "Policy",
      "items": [
        "protocol/terms_of_use",
        "protocol/privacy_policy",
        "protocol/data_processing",
      ]
    },
    {
      "type": "category",
      "label": "Reference",
      "items": [
        "reference/service_difference",
        "reference/file_schema_format",
        "reference/kafka_msg_format_type",
        "reference/java_jdbc_types",
        "reference/db2_incr_ddl_notice",
        "reference/rds_mysql_ram_least_privilege"
      ]
    }
  ],
};

export default sidebars;
