import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   'intro'
  // ],

  // 主文档 sidebar - 默认显示
  communitySidebar: [
    {
      type: "category",
      label: "产品介绍",
      items: [
        "intro/product_intro",
        "intro/product_advantage",
        "intro/product_func",
        "intro/product_structure",
        "intro/product_nouns",
        "intro/contact_us"
      ],
    },
    {
      type: "category",
      label: "安装/升级",
      items: [
        "maintain/install_require",
        {
          type: "category",
          label: "TGZ 版",
          items: ["maintain/install_tgz", "maintain/upgrade_tgz"],
        },
        {
          type: "category",
          label: "Docker 版",
          items: [
            "maintain/install_docker",
            "maintain/upgrade_docker",
            "maintain/uninstall_docker",
          ],
        },
        "maintain/license",
      ],
    },
    {
      type: "category",
      label: "快速开始",
      items: ["quick/quick_start"],
    },
    {
      type: "category",
      label: "功能特性",
      items: [
        {
          type: "category",
          label: "数据查询",
          items: [
            "console/console_editor",
            "console/console_execute",
            "console/obj_browser",
            "console/obj_ddl",
            "console/operate/console_visual_editor",
            "console/sql_rules",
          ],
        },
        {
          type: "category",
          label: "数据脱敏",
          items: [
            "datamask/datamask_about",
            "datamask/datamask_policy",
            "datamask/datamask_dynamic",
            "datamask/datamask_exemption",
          ],
        },
        {
          type: "category",
          label: "数据库 CI/CD",
          items: [
            "devops/devops_about",
            "devops/devops_project",
            "devops/devops_flow",
            "devops/devops_change",
            "devops/devops_trigger",
            "devops/devops_callback",
            "devops/devops_service",
          ],
        },
        {
          type: "category",
          label: "工单系统",
          items: [
            "approval/approval_about",
            "approval/approval_and_execution",
            "approval/approval_detail",
            "approval/approval_list",
            "approval/approval_setting",
            "approval/approval_submit",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "系统管理",
      items: [
        {
          type: "category",
          label: "安全",
          items: [
            "operation/accounts",
            "operation/roles_prem",
            "operation/security_policy",
            "operation/audit",
          ],
        },
        {
          type: "category",
          label: "环境",
          items: ["operation/environment", "operation/cluster_worker"],
        },
        {
          type: "category",
          label: "数据源",
          items: ["operation/dsmanager"],
        },
      ],
    },
    {
      type: "category",
      label: "集成",
      items: [
        {
          type: "category",
          label: "单点登录 SSO",
          items: [
            "integrations/sso/sso_ldap",
            "integrations/sso/sso_ad",
            "integrations/sso/sso_oidc",
            "integrations/sso/sso_dingtalk",
            "integrations/sso/sso_feishu",
            "integrations/sso/sso_wechat",
          ],
        },
        {
          type: "category",
          label: "审批引擎",
          items: [
            "integrations/approval/dingtalk_approval",
            "integrations/approval/feishu_approval",
            "integrations/approval/wechat_approval",
          ],
        },
        {
          type: "category",
          label: "CI/CD 变更源",
          items: ["integrations/devops/devops_cicd_gitee"],
        },
        {
          type: "category",
          label: "消息服务",
          items: [
            "integrations/devops/devops_im_dingtalk",
            "integrations/devops/devops_im_feishu",
            "integrations/devops/devops_im_wechat",
          ],
        },
        {
          type: "category",
          label: "产品集成",
          items: ["integrations/cloudcanal"],
        },
      ],
    },
    {
        type: 'category',
        label: '版本说明',
        link: {
            type: 'generated-index',
            title: 'CloudDM 版本说明',
            description: '查看 CloudDM 各个版本的更新说明、功能特性和修复内容'
        },
        items: [
            "releaseinfo/team_3_4_0_0",
            "releaseinfo/team_3_3_0_0",
            "releaseinfo/team_3_2_0_0",
            "releaseinfo/team_3_1_0_0",
            "releaseinfo/team_3_0_0_0",
            "releaseinfo/team_2_8_1_0",
            "releaseinfo/team_2_8_0_0",
            "releaseinfo/team_2_7_1_0",
            "releaseinfo/team_2_7_0_0",
            'releaseinfo/team_2_6_0_0',
            'releaseinfo/team_2_5_0_0',
            'releaseinfo/team_2_4_0_0',
            'releaseinfo/team_2_3_2_0',
            'releaseinfo/team_2_3_1_0',
            'releaseinfo/team_2_3_0_0',
            'releaseinfo/team_2_2_0_0',
            'releaseinfo/team_2_1_1_0',
            'releaseinfo/team_2_1_0_0',
            'releaseinfo/team_2_0_0_0',
            'releaseinfo/team_1_4_4_0',
            'releaseinfo/team_1_4_3_0',
            'releaseinfo/team_1_4_0_0',
            'releaseinfo/team_1_3_0_0',
            'releaseinfo/team_1_2_0_0'
        ],
    },
    {
      type: "category",
      label: "FAQ",
      items: [
        "faq/info_modify",
        "faq/docker_failed",
        "faq/upgrade_to_2_x",
        "faq/init_mysql_5_6_failed",
      ],
    },
    {
      type: "category",
      label: "协议",
      items: [
      "protocol/terms_of_use",
      "protocol/privacy_policy",
      ],
    },
  ],

  // 个人版版本说明 sidebar - 专门用于个人版版本信息页面
  personalSidebar: [
    {
      type: "category",
      label: "个人版版本说明",
      link: {
        type: "generated-index",
        title: "CloudDM 个人版版本说明",
        description:
          "查看 CloudDM 个人版各个版本的更新说明、功能特性和修复内容",
      },
      items: [
        "releasenote_personal/desktop_latest",
        "releasenote_personal/desktop_3_0_7",
        "releasenote_personal/desktop_3_0_6",
        "releasenote_personal/desktop_3_0_5",
        "releasenote_personal/desktop_3_0_4",
        "releasenote_personal/desktop_3_0_3",
        "releasenote_personal/desktop_3_0_2",
        "releasenote_personal/desktop_3_0_1",
        "releasenote_personal/desktop_3_0_0",
        "releasenote_personal/desktop_2_9_0",
        "releasenote_personal/desktop_2_8_4",
        "releasenote_personal/desktop_2_8_3",
        "releasenote_personal/desktop_2_8_2",
        "releasenote_personal/desktop_2_8_1",
        "releasenote_personal/desktop_2_8_0",
        "releasenote_personal/desktop_2_7_0",
        "releasenote_personal/desktop_2_6_0",
        "releasenote_personal/desktop_2_5_0",
        "releasenote_personal/desktop_2_4_5",
        "releasenote_personal/desktop_2_4_4",
        "releasenote_personal/desktop_2_4_3",
        "releasenote_personal/desktop_2_4_2",
        "releasenote_personal/desktop_2_4_1",
        "releasenote_personal/desktop_2_4_0",
        "releasenote_personal/desktop_2_3_4",
        "releasenote_personal/desktop_2_3_3",
        "releasenote_personal/desktop_2_3_2",
        "releasenote_personal/desktop_2_3_1",
        "releasenote_personal/desktop_2_3_0",
        "releasenote_personal/desktop_2_2_0",
        "releasenote_personal/desktop_2_1_3",
        "releasenote_personal/desktop_2_1_2",
        "releasenote_personal/desktop_2_1_1",
        "releasenote_personal/desktop_2_1_0",
        "releasenote_personal/desktop_2_0_5",
        "releasenote_personal/desktop_2_0_4",
        "releasenote_personal/desktop_2_0_3",
        "releasenote_personal/desktop_2_0_2",
      ],
    },
  ],
};

export default sidebars;
