import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   'intro'
  // ],
  communitySidebar: [
    {
      "type": "category",
      "label": "介绍",
      "items": [
        "intro/product_intro",
        "intro/product_version",
        "intro/product_scenarios",
        "intro/product_advantage",
        "intro/product_arch",
        "intro/product_nouns"
      ]
    },
    {
      "type": "doc",
      "id": "price/product_price",
    },
    {
      "type": "doc",
      "id": "license/license_use"
    },
    {
      "type": "doc",
      "id": "quick/quick_start"
    },
    {
      "type": "doc",
      "id": "quick/quick_start_mgr"
    },
    {
      "type": "doc",
      "id": "quick/quick_start_byoc"
    },
    {
      "type": "category",
      "label": "使用手册",
      "items": [

        {
          "type": "category",
          "label": "同步任务",
          "items": [
            {
              "type": "category",
              "label": "任务创建",
              "items": [
                "operation/job_manage/create_job/create_full_incre_task",
                "operation/job_manage/create_job/create_process_job",
                "operation/job_manage/create_job/create_data_filter_job",
                "operation/job_manage/create_job/create_db_sync_job",
                "operation/job_manage/create_job/create_period_full_job",
                "operation/job_manage/create_job/create_verification_correction_job"
              ]
            },
            {
              "type": "category",
              "label": "任务管理",
              "items": [
                "operation/job_manage/job_op/job_life_cycle_manage",
                "operation/job_manage/job_op/job_detail",
                "operation/job_manage/job_op/job_log",
                "operation/job_manage/job_op/job_monitor",
                "operation/job_manage/job_op/job_params",
                "operation/job_manage/job_op/edit_job",
                "operation/job_manage/job_op/job_position",
                "operation/job_manage/job_op/job_schedule",
                "operation/job_manage/job_op/job_replay",
                "operation/job_manage/job_op/job_alarm",
                "operation/job_manage/job_op/create_similar_job",
                "operation/job_manage/job_op/debug_customer_code",
                "operation/job_manage/job_op/log_in_customer_code",
                "operation/job_manage/job_op/job_restart_record",
                "operation/job_manage/job_op/job_transfer",
                "operation/job_manage/job_op/job_group",
                "operation/job_manage/job_op/change_job_setting",
                "operation/job_manage/job_op/data_transform",
                "operation/job_manage/job_op/visual_widetable_create",
                //"operation/job_manage/job_op/param_template"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "同步设置",
          "items": [
            {
              "type": "category",
              "label": "机器管理",
              "items": [
                "operation/job_setting/worker_manage/cluster_manage",
                "operation/job_setting/worker_manage/add_worker_self_maintain",
                "operation/job_setting/worker_manage/worker_monitor_alarm",
                "operation/job_setting/worker_manage/worker_log",
                "operation/job_setting/worker_manage/job_setting",
                "operation/job_setting/worker_manage/oversell_mac_memory"
              ]
            },
            "operation/job_setting/check_alarm_log",
            "operation/job_setting/exception_manage",
            "operation/job_setting/console_job_manage",
            "operation/job_setting/fsm_manage",
            // "operation/job_setting/user_manage",
            "operation/job_setting/operate_audit"
          ]
        },
        {
          "type": "category",
          "label": "数据源管理",
          "items": [
            "operation/datasource_manage/add_self_maintain_ds",
            "operation/datasource_manage/add_aliyun_ds",
            "operation/datasource_manage/add_aws_ds",
            "operation/datasource_manage/add_azure_ds",
            "operation/datasource_manage/add_huaweiyun_ds",
            "operation/datasource_manage/ds_manage",
            "operation/datasource_manage/set_ssh_tunnel"
          ]
        },
        {
          "type": "category",
          "label": "系统管理",
          "items": [
            {
              "type": "category",
              "label": "账号与权限",
              "items": [
                "operation/system_manage/account_and_auth/account_and_auth",
                "operation/system_manage/account_and_auth/res_auth",
                "operation/system_manage/account_and_auth/role_auth"
              ]
            },
            {
              "type": "category",
              "label": "统一认证SSO",
              "items": [
                'operation/system_manage/sso/sso_ldap',
                'operation/system_manage/sso/sso_oidc',
                'operation/system_manage/sso/sso_ad',
                'operation/system_manage/sso/sso_dingtalk',
                'operation/system_manage/sso/sso_feishu',
                'operation/system_manage/sso/sso_wechat',
              ]
            },
            "operation/system_manage/mfa_usage",
            "operation/system_manage/env_manage",
            "operation/system_manage/operation_audit_rdp",
            "operation/system_manage/preference",
            "operation/system_manage/third_party_setting"
          ]
        }

      ]
    },
    {
      "type": "category",
      "label": "数据链路",
      "items": [
        "dataMigrationAndSync/datasource_version",
        {
          "type": "category",
          "label": "通用参数与功能",
          "items": [
            "dataMigrationAndSync/param_and_func/param_guide",
            "dataMigrationAndSync/param_and_func/print_message_detail",
            "dataMigrationAndSync/param_and_func/zero_time_replace",
            "dataMigrationAndSync/param_and_func/full_write_rps_limit",
            "dataMigrationAndSync/param_and_func/perf_param",
            "dataMigrationAndSync/param_and_func/skip_write_error",
            "dataMigrationAndSync/param_and_func/skip_ddl_error",
            "dataMigrationAndSync/param_and_func/adjust_task_spec",
            "dataMigrationAndSync/param_and_func/sync_online_ddl",
            "dataMigrationAndSync/param_and_func/job_no_autoreboot",
            "dataMigrationAndSync/param_and_func/float_check"
          ]
        },
        "dataMigrationAndSync/monitor",
        {
          "type": "category",
          "label": "源端数据源",
          "items": [
            "dataMigrationAndSync/connection/mysql2",
            "dataMigrationAndSync/connection/mariadb2",
            "dataMigrationAndSync/connection/auroraformysql2",
            "dataMigrationAndSync/connection/polardbmysql2",
            "dataMigrationAndSync/connection/oracle2",
            "dataMigrationAndSync/connection/hana2",
            "dataMigrationAndSync/connection/redis2",
            "dataMigrationAndSync/connection/postgresql2",
            "dataMigrationAndSync/connection/auroraforpg",
            "dataMigrationAndSync/connection/opengauss2",
            "dataMigrationAndSync/connection/sqlserver2",
            "dataMigrationAndSync/connection/oceanbase2",
            "dataMigrationAndSync/connection/tidb2",
            "dataMigrationAndSync/connection/polardbx2",
            "dataMigrationAndSync/connection/db22",
            "dataMigrationAndSync/connection/starrocks2",
            "dataMigrationAndSync/connection/mongodb2",
            "dataMigrationAndSync/connection/kafka2",
            "dataMigrationAndSync/connection/automq2",
            "dataMigrationAndSync/connection/rocketmq2",
            "dataMigrationAndSync/connection/rabbitmq2",
            "dataMigrationAndSync/connection/tunnel2",
            "dataMigrationAndSync/connection/obfororacle2",
            "dataMigrationAndSync/connection/pulsar2",
            "dataMigrationAndSync/connection/tdengine2",
            "dataMigrationAndSync/connection/googledrive2",
            "dataMigrationAndSync/connection/dameng2",
            "dataMigrationAndSync/connection/gaussdb2",
            "dataMigrationAndSync/connection/dynamodb2",
            // "dataMigrationAndSync/source/postgresql",
            // "dataMigrationAndSync/source/sqlserver",
            // "dataMigrationAndSync/source/greenplum",
            // "dataMigrationAndSync/source/kafka",
            // "dataMigrationAndSync/source/rocketmq",
            // "dataMigrationAndSync/source/rabbitmq",
            // "dataMigrationAndSync/source/mongodb",
            // "dataMigrationAndSync/source/tunnel",
            // "dataMigrationAndSync/source/starrocks",
            // "dataMigrationAndSync/source/tidb",
            // "dataMigrationAndSync/source/db2"
          ]
        },
        // },
        // {
        //     "type": "category",
        //     "label": "对端数据源",
        //     "items": [
        //         "dataMigrationAndSync/target/MySQL",
        //         "dataMigrationAndSync/target/TiDB",
        //         "dataMigrationAndSync/target/PostgreSQL",
        //         "dataMigrationAndSync/target/Greenplum",
        //         "dataMigrationAndSync/target/ElasticSearch",
        //         "dataMigrationAndSync/target/ClickHouse",
        //         "dataMigrationAndSync/target/Kafka",
        //         "dataMigrationAndSync/target/RocketMQ",
        //         "dataMigrationAndSync/target/RabbitMQ",
        //         "dataMigrationAndSync/target/Hive",
        //         "dataMigrationAndSync/target/Oracle",
        //         "dataMigrationAndSync/target/Kudu",
        //         "dataMigrationAndSync/target/MongoDB",
        //         "dataMigrationAndSync/target/SQLServer",
        //         "dataMigrationAndSync/target/Redis",
        //         "dataMigrationAndSync/target/StarRocks",
        //         "dataMigrationAndSync/target/Doris",
        //         "dataMigrationAndSync/target/OceanBase",
        //         "dataMigrationAndSync/target/PolarDB-X",
        //         "dataMigrationAndSync/target/Tunnel",
        //         "dataMigrationAndSync/target/ADB for MySQL",
        //         "dataMigrationAndSync/target/PolarDB for MySQL",
        //         "dataMigrationAndSync/target/GaussDB for OpenGauss",
        //         "dataMigrationAndSync/target/GaussDB for MySQL"
        //     ]
        // }
        {
          "type": "category",
          "label": "数据源配置与功能",
          "items": [
            {
              "type": "category",
              "label": "MySQL",
              "items": [
                "dataMigrationAndSync/datasource_func/MySQL/privs_for_mysql",
                "dataMigrationAndSync/datasource_func/MySQL/open_mysql_heartbeat"
              ]
            },
            {
              "type": "category",
              "label": "Oracle",
              "items": [
                "dataMigrationAndSync/datasource_func/Oracle/privs_for_oracle",
                "dataMigrationAndSync/datasource_func/Oracle/oracle_dg_mode",
                "dataMigrationAndSync/datasource_func/Oracle/prepare_for_oracle_logminer",
                "dataMigrationAndSync/datasource_func/Oracle/prepare_for_oracle_olr"
              ]
            },
            {
              "type": "category",
              "label": "Dameng",
              "items": [
                "dataMigrationAndSync/datasource_func/Dameng/prepare_for_dameng_logminer",
                "dataMigrationAndSync/datasource_func/Dameng/privs_for_dameng"
              ]
            },
            {
              "type": "category",
              "label": "PostgreSQL",
              "items": [
                "dataMigrationAndSync/datasource_func/PostgreSQL/privs_for_pg",
                "dataMigrationAndSync/datasource_func/PostgreSQL/open_pg_heartbeat",
                "dataMigrationAndSync/datasource_func/PostgreSQL/set_pg_replica_identity"
              ]
            },
            {
              "type": "category",
              "label": "GaussDB",
              "items": [
                "dataMigrationAndSync/datasource_func/GaussDB/privs_for_gaussdb"
              ]
            },
            {
              "type": "category",
              "label": "SQL Server",
              "items": [
                "dataMigrationAndSync/datasource_func/SqlServer/privs_for_sqlserver",
                "dataMigrationAndSync/datasource_func/SqlServer/sync_cdc_cdc",
                "dataMigrationAndSync/datasource_func/SqlServer/update_multi_pos"
              ]
            },
            {
              "type": "category",
              "label": "StarRocks",
              "items": [
                "dataMigrationAndSync/datasource_func/StarRocks/starrocks_partition"
              ]
            },
            {
              "type": "category",
              "label": "Kafka",
              "items": [
                "dataMigrationAndSync/datasource_func/Kafka/privs_for_kafka",
                "dataMigrationAndSync/datasource_func/Kafka/open_kafka_heartbeat"
              ]
            },
            {
              "type": "category",
              "label": "TiDB",
              "items": [
                "dataMigrationAndSync/datasource_func/TiDB/privs_for_tidb"
              ]
            },
            {
              "type": "category",
              "label": "MongoDB",
              "items": [
                "dataMigrationAndSync/datasource_func/MongoDB/privs_for_mongo",
                "dataMigrationAndSync/datasource_func/MongoDB/open_mongodb_heartbeat"
              ]
            },
            {
              "type": "category",
              "label": "ElasticSearch",
              "items": [
                "dataMigrationAndSync/datasource_func/ElasticSearch/prepare_for_es_as_src"
              ]
            },
            {
              "type": "category",
              "label": "Iceberg",
              "items": [
                "dataMigrationAndSync/datasource_func/Iceberg/props_for_iceberg_ds"
              ]
            },
            {
              "type": "category",
              "label": "Paimon",
              "items": [
                "dataMigrationAndSync/datasource_func/Paimon/props_for_paimon_ds"
              ]
            },
            {
              "type": "category",
              "label": "SAP HANA",
              "items": [
                "dataMigrationAndSync/datasource_func/Hana/privs_for_hana",
                "dataMigrationAndSync/datasource_func/Hana/sap_hana_ddl"
              ]
            },
            {
              "type": "category",
              "label": "TDengine",
              "items": [
                "dataMigrationAndSync/datasource_func/TDengine/privs_for_tdengine"
              ]
            },
            {
              "type": "category",
              "label": "Db2",
              "items": [
                "dataMigrationAndSync/datasource_func/Db2/prepare_for_db2"
              ]
            },
            {
              "type": "category",
              "label": "Redis",
              "items": [
                "dataMigrationAndSync/datasource_func/Redis/redis_check_simple",
                "dataMigrationAndSync/datasource_func/Redis/performance_optimization_redis_src"
              ]
            },
            {
              "type": "category",
              "label": "Google Drive",
              "items": [
                "dataMigrationAndSync/datasource_func/GoogleDrive/privs_for_googledrive",
                "dataMigrationAndSync/datasource_func/GoogleDrive/prepare_for_google_cloud"
              ]
            },
            {
              "type": "category",
              "label": "DynamoDB",
              "items": [
                  "dataMigrationAndSync/datasource_func/DynamoDB/privs_for_dynamodb"
              ]
          },
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "产品运维(私有部署)",
      "items": [
        {
          "type": "category",
          "label": "Docker 部署",
          "items": [
            "productOP/docker/install_linux_macos",
            "productOP/docker/upgrade_version",
            "productOP/docker/ha_install"
          ]
        },
        {
          "type": "category",
          "label": "K8S 部署",
          "items": [
            "productOP/kubernetes/install_on_k8s",
            "productOP/kubernetes/upgrade_version_on_k8s",
            "productOP/kubernetes/ha_install_on_k8s"
          ]
        },
        {
          "type": "category",
          "label": "TGZ 部署",
          "items": [
            "productOP/tgz/firstinstall_with_tgz",
            "productOP/tgz/upgrade_tgz",
            "productOP/tgz/ad_worker_tgz"
          ]
        },
        {
          "type": "category",
          "label": "日常运维",
          "items": [
            "productOP/dailyOP/change_mysql",
            "productOP/dailyOP/change_mysql_on_k8s",
            "productOP/dailyOP/change_on_premise_password",
            "productOP/dailyOP/change_verify_code_777777",
            "productOP/dailyOP/change_ak_sk",
            "productOP/dailyOP/connect_to_metadb",
            "productOP/dailyOP/get_log",
            "productOP/dailyOP/operate_compose",
            "productOP/dailyOP/change_console_sidecar_mem",
            "productOP/dailyOP/audit_log",
            "productOP/dailyOP/alarm_conf",
            "productOP/dailyOP/create_dingding_group",
            "productOP/dailyOP/create_feishu_group",
            "productOP/dailyOP/create_discord_group",
            "productOP/dailyOP/create_slack_group",
            "productOP/dailyOP/create_custom_alarm",
            "productOP/dailyOP/add_sms_alert",
            "productOP/dailyOP/add_voice_alert",
            "productOP/dailyOP/upgrade_to_rdp",
            "productOP/dailyOP/minimal_k8s_for_cc",
            "productOP/dailyOP/change_console_config",
            "productOP/dailyOP/set_schedule_strategy",
            "productOP/dailyOP/auto_logout_set",
            "productOP/dailyOP/clear_worker_log"
          ]
        },
        {
          "type": "category",
          "label": "平台拓展",
          "items": [
            "productOP/platform/extend_clouddm_team",
            "productOP/platform/add_job_grafana_dashbord"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "产品运维(SaaS BYOC)",
      "items": [
        {
          "type": "category",
          "label": "客户端部署",
          "items": [
            "productOpByoc/docker/install_worker_docker",
            "productOpByoc/docker/upgrade_worker_docker",
            "productOpByoc/docker/uninstall_worker_docker"
          ]
        },
        {
          "type": "category",
          "label": "日常运维",
          "items": [
            "productOpByoc/dailyOp/get_log",
            "productOpByoc/dailyOp/clear_worker_log",
            "productOpByoc/dailyOp/change_worker_mem"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "最佳实践",
      "items": [
        "bestPractice/file_to_aliyun_pg_vector",
        "bestPractice/pg_vector_to_rag_api",
        "bestPractice/mysql_loop_data_sync",
        "bestPractice/redis_loop_data_sync",
        "bestPractice/opengauss_pg_loop_data_sync",
        "bestPractice/data_gather_use_virtual_cols",
        "bestPractice/http_internet_data_sync",
        "bestPractice/http_internet_data_sync_2",
        "bestPractice/encrypt_data_when_sync",
        "bestPractice/mysql_clickhouse_sync",
        "bestPractice/verification_and_correction",
        "bestPractice/mysql_kafka_sync",
        "bestPractice/mysql_redis_sync",
        "bestPractice/api_write_data_sync",
        "bestPractice/one_cluster_13k_task_test",
        "bestPractice/use_aliyun_emr_sr_doris",
        "bestPractice/time_schedule_full",
        "bestPractice/use_open_api_to_integrate_cc",
        "bestPractice/oracle_clickhouse_sync",
        "bestPractice/migrate_mysql_systable",
        "bestPractice/mysql_iceberg_sync",
      ]
    },
    {
      "type": "category",
      "label": "开放API",
      "items": [
        {
          "type": "doc",
          "id": "openCenter/openApi/apiUseReference/api_common_parameters"
        },
        {
          "type": "category",
          "label": "常量获取API",
          "items": [
            "openCenter/openApi/constApi/api_constant_cachevalueformats",
            "openCenter/openApi/constApi/api_constant_cktableengines",
            "openCenter/openApi/constApi/api_constant_dscharset",
            "openCenter/openApi/constApi/api_constant_dsdeploytypes",
            "openCenter/openApi/constApi/api_constant_dsmappingmeta",
            "openCenter/openApi/constApi/api_constant_dspostype",
            "openCenter/openApi/constApi/api_constant_dstdstype",
            "openCenter/openApi/constApi/api_constant_listdatajobtype",
            "openCenter/openApi/constApi/api_constant_listspecs",
            "openCenter/openApi/constApi/api_constant_listdatataskstates",
            "openCenter/openApi/constApi/api_constant_listdatataskstatuses",
            "openCenter/openApi/constApi/api_constant_mqvalueformats",
            "openCenter/openApi/constApi/api_constant_srcdstype",
            "openCenter/openApi/constApi/api_constant_transformjobtype",
            "openCenter/openApi/constApi/api_constant_valueformatstemplate"
          ]
        },
        {
          "type": "category",
          "label": "机器集群API",
          "items": [
            "openCenter/openApi/clusterApi/api_cluster_listclusters",
            "openCenter/openApi/clusterApi/api_cluster_listworkers",
            "openCenter/openApi/clusterApi/api_cluster_createandinstallworker",
            "openCenter/openApi/clusterApi/api_cluster_operateworkersclient"
          ]
        },
        {
          "type": "category",
          "label": "数据源API",
          "items": [
            "openCenter/openApi/dataSourceApi/api_datasource_addds",
            "openCenter/openApi/dataSourceApi/api_datasource_listds",
            "openCenter/openApi/dataSourceApi/api_datasource_deleteaccount",
            "openCenter/openApi/dataSourceApi/api_datasource_updateaccountandpassword",
            "openCenter/openApi/dataSourceApi/api_datasource_updatealiyunrdsaksk",
            "openCenter/openApi/dataSourceApi/api_datasource_updatedatasourcedesc",
            "openCenter/openApi/dataSourceApi/api_datasource_updateprivatehost",
            "openCenter/openApi/dataSourceApi/api_datasource_updatepublichost",
            "openCenter/openApi/dataSourceApi/api_datasource_queryds",
            "openCenter/openApi/dataSourceApi/api_datasource_connectds",
            "openCenter/openApi/dataSourceApi/api_datasource_listdbs",
            "openCenter/openApi/dataSourceApi/api_datasource_tablecount",
            "openCenter/openApi/dataSourceApi/api_datasource_listtables",
            "openCenter/openApi/dataSourceApi/api_datasource_listcols",
            "openCenter/openApi/dataSourceApi/api_datasource_listuniqs",
            "openCenter/openApi/dataSourceApi/api_datasource_listtypemapping",
            "openCenter/openApi/dataSourceApi/api_datasource_deleteds",
            "openCenter/openApi/dataSourceApi/api_datasource_querydsconfig",
            "openCenter/openApi/dataSourceApi/api_datasource_upsertdsconfig"
          ]
        },
        {
          "type": "category",
          "label": "数据任务API",
          "items": [
            "openCenter/openApi/dataTaskApi/api_datajob_list",
            "openCenter/openApi/dataTaskApi/api_datajob_query",
            "openCenter/openApi/dataTaskApi/api_datajob_queryjobschema",
            "openCenter/openApi/dataTaskApi/api_datajob_start",
            "openCenter/openApi/dataTaskApi/api_datajob_stop",
            "openCenter/openApi/dataTaskApi/api_datajob_restart",
            "openCenter/openApi/dataTaskApi/api_datajob_replay",
            "openCenter/openApi/dataTaskApi/api_datajob_attachincretask",
            "openCenter/openApi/dataTaskApi/api_datajob_detachincretask",
            "openCenter/openApi/dataTaskApi/api_datajob_activefsm",
            "openCenter/openApi/dataTaskApi/api_datajob_precheckbasic",
            "openCenter/openApi/dataTaskApi/api_datajob_precheckdetail",
            "openCenter/openApi/dataTaskApi/api_datajob_create",
            "openCenter/openApi/dataTaskApi/api_datajob_updatedesc",
            "openCenter/openApi/dataTaskApi/api_datajob_updatelevel",
            "openCenter/openApi/dataTaskApi/api_datajob_updatetransferobjnew",
            "openCenter/openApi/dataTaskApi/api_datajob_updatetransferobjnewfull",
            "openCenter/openApi/dataTaskApi/api_datajob_delete",
            "openCenter/openApi/dataTaskApi/api_datajob_schema",
            "openCenter/openApi/dataTaskApi/api_datajob_mapping",
            "openCenter/openApi/dataTaskApi/api_datajob_listkvconfigsbyjobid",
            "openCenter/openApi/dataTaskApi/api_datajob_upsertkvconfigs"
          ]
        },
        {
          "type": "category",
          "label": "元数据API",
          "items": [
            "openCenter/openApi/schemaApi/api_schema_querybytransferobjname"
          ]
        },
        {
          "type": "category",
          "label": "异步任务API",
          "items": [
            "openCenter/openApi/asyncTaskApi/api_consolejob_queryconsolejob",
            "openCenter/openApi/asyncTaskApi/api_consolejob_retrytask"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "版本说明",
      "items": [
        "releaseNote/rn-cloudcanal-5-2-1-0",
        "releaseNote/rn-cloudcanal-5-2-0-0",
        "releaseNote/rn-cloudcanal-5-1-0-0",
        "releaseNote/rn-cloudcanal-5-0-0-0",
        "releaseNote/rn-cloudcanal-4-9-0-0",
        "releaseNote/rn-cloudcanal-4-8-0-0",
        "releaseNote/rn-cloudcanal-4-7-2-0",
        "releaseNote/rn-cloudcanal-4-7-1-0",
        "releaseNote/rn-cloudcanal-4-7-0-0",
        "releaseNote/rn-cloudcanal-4-6-0-0",
        "releaseNote/rn-cloudcanal-4-5-0-0",
        "releaseNote/rn-cloudcanal-4-4-2-0",
        "releaseNote/rn-cloudcanal-4-4-1-0",
        "releaseNote/rn-cloudcanal-4-4-0-0",
        "releaseNote/rn-cloudcanal-4-3-0-0",
        "releaseNote/rn-cloudcanal-4-2-1-0",
        "releaseNote/rn-cloudcanal-4-2-0-0",
        "releaseNote/rn-cloudcanal-4-1-1-0",
        "releaseNote/rn-cloudcanal-4-0-1-0",
        "releaseNote/rn-cloudcanal-4-0-0-0",
        "releaseNote/rn-cloudcanal-3-4-1-0",
        "releaseNote/rn-cloudcanal-3-4-0-0",
        "releaseNote/rn-cloudcanal-3-3-4-0",
        "releaseNote/rn-cloudcanal-3-3-3-0",
        "releaseNote/rn-cloudcanal-3-3-2-0",
        "releaseNote/rn-cloudcanal-3-3-1-0",
        "releaseNote/rn-cloudcanal-3-3-0-0",
        "releaseNote/rn-cloudcanal-3-2-1-0",
        "releaseNote/rn-cloudcanal-3-1-0-0",
        "releaseNote/rn-cloudcanal-3-0-0-10",
        "releaseNote/rn-cloudcanal-2-8-0-0",
        "releaseNote/rn-cloudcanal-2-7-1-5",
        "releaseNote/rn-cloudcanal-2-7-0-0",
        "releaseNote/rn-cloudcanal-2-6-1-0",
        "releaseNote/rn-cloudcanal-2-6-0-0",
        "releaseNote/rn-cloudcanal-2-5-0-0",
        "releaseNote/rn-cloudcanal-2-4-0-0",
        "releaseNote/rn-cloudcanal-2-3-4-0",
        "releaseNote/rn-cloudcanal-2-3-3-0",
        "releaseNote/rn-cloudcanal-2-3-1-0",
        "releaseNote/rn-cloudcanal-2-3-0-0",
        "releaseNote/rn-cloudcanal-2-2-6-0",
        "releaseNote/rn-cloudcanal-2-2-5-0",
        "releaseNote/rn-cloudcanal-2-2-4-0",
        "releaseNote/rn-cloudcanal-2-2-3-0",
        "releaseNote/rn-cloudcanal-2-2-2-0",
        "releaseNote/rn-cloudcanal-2-2-1-0",
        "releaseNote/rn-cloudcanal-2-2-0-7",
        "releaseNote/rn-cloudcanal-2-2-0-4",
        "releaseNote/rn-cloudcanal-2-1-0-14",
        "releaseNote/rn-cloudcanal-2-0-1-0",
        "releaseNote/rn-cloudcanal-1-2-1",
        "releaseNote/rn-cloudcanal-1-2-0",
        "releaseNote/rn-cloudcanal-1-1-0",
        "releaseNote/rn-cloudcanal-1-0-3",
        "releaseNote/rn-cloudcanal-1-0-2",
        "releaseNote/rn-cloudcanal-1-0-1",
        "releaseNote/rn-cloudcanal-1-0-0"
      ]
    },
    {
      "type": "category",
      "label": "FAQ",
      "items": [
        "faq/cloudcanal_faq_list",
        "faq/performance_optimization",
        "faq/solve_db_connect_fail",
        "faq/solve_schedule_task_fail",
        "faq/solve_incre_task_delay",
        "faq/solve_data_inconsistent",
        "faq/solve_task_communicate_timeout",
        "faq/solve_task_can_not_delete",
        "faq/solve_mysql_src_json_invalid",
        "faq/solve_hana_test_connection_fail",
        "faq/solve_sqlserver_tls",
        "faq/solve_install_fail_docker",
        "faq/solve_mysql_src_could_not_find_binlog",
        "faq/solve_sr_dr_dst_writer_http_host",
        "faq/solve_get_meta_time_out",
        "faq/solve_auto_deploy_node_by_jdk_error",
        "faq/solve_login_empty_key_error",
        "faq/solve_structure_migration_error",
        "faq/solve_access_denied_schema",
        "faq/solve_activate_data_truncation"
      ]
    },
    {
      "type": "category",
      "label": "协议",
      "items": [
        "protocol/terms_of_use",
        "protocol/privacy_policy"
      ]
    },
    {
      "type": "category",
      "label": "附录",
      "items": [
        "reference/resource_download",
        "reference/service_difference",
        "reference/apply_code",
        "reference/license_overdue",
        "reference/kafka_msg_format_type",
        "reference/debezium_json_notice",
        "reference/file_schema_format",
        "reference/db2_incr_ddl_notice",
        "reference/rds_mysql_ram_least_privilege",
        "reference/java_jdbc_types"
      ]
    }
  ],
  
};

export default sidebars;
